[versions]
# libraries
junit = "5.13.4"
junit4 = "4.13.2"
junit_platform = "1.13.4"
errorprone_core = "2.42.0"
nullaway = "0.12.10"
jspecify = "1.0.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.11.0"
kotlin = "2.2.20"
errorprone = "4.3.0"

[libraries]
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit_platform" }
errorprone_core = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorprone_core" }
nullaway = { group = "com.uber.nullaway", name = "nullaway", version.ref = "nullaway" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone" }
